---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template to install CloudWagentAgent on windows. It was validated on windows 2016'
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: m5.2xlarge
    ConstraintDescription: must be a valid EC2 instance type.
  InstanceAMI:
    Description: Managed AMI ID for EC2 Instance
    Type : String
    Default: ami-0e60ba06451c1b981
  InstanceProfile: 
    Type: String
    Description: Enter an instance profile that allows the intance to create the tags on itself


  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.



###the instance needs an instance profile with permissions to add tags
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref InstanceProfile
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: KeyName
      ImageId:
        Ref: InstanceAMI
##### we apply a tag to the instance mixing both instance id and ip
      UserData:
        Fn::Base64: !Sub | 
          <powershell>
          import-module awspowershell
          Start-Sleep -s 40
          $privateIp = Invoke-RestMethod -uri http://169.254.169.254/latest/meta-data/local-ipv4
          $privateIp | Out-File c:\preprivateip.txt
          $last3charsip = $privateIp.Substring($privateIp.Length - 3)
          $InstanceId = Invoke-RestMethod -uri http://169.254.169.254/latest/meta-data/instance-id
          $last4charsinstance = $InstanceId.Substring($InstanceId.Length - 4)
          $InstanceId | Out-File c:\preinstanceid.txt
          $last4charsinstance | Out-File c:\instanceid.txt
          $last3charsip | Out-File c:\privateIp.txt
          $tag = New-Object Amazon.EC2.Model.Tag
          $tag.Key = "myTag"
          $tag.Value = $last4charsinstance+$last3charsip
          New-EC2Tag -Resource $InstanceId -Tag $tag 
          </powershell>

